### PR TITLE
Fix `Worker was terminated` error on unmount

### LINKED ISSUE #1062: Error handling - PDFJS worker termination while loading and unmounting component.
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Sorry for the bump but is there any known solutions to this? This is referenced in this closed issue but seems as if the issue is stale and have a newer build then what is referenced here. It does not appear to be caught in the onLoadError. 

https://github.com/wojtekmaj/react-pdf/issues/651

image

image

image

image

### Steps to reproduce

1. Throttle Network speed in browser
2. Load a PDF
3. Navigate to another page prior to the PDF completing forcing the component to unmount
4. Get error in console

### Expected behavior

Graceful error handling or the ability to do a try catch, or an abort controller equivalent. 

### Actual behavior

React is not happy 

### Additional information

I happen to be using Gatsby, but this should persist even in vanilla React environments

### Environment

- **Browser (if applicable)**: Chrome Version 106.0.5249.103
- **React-PDF version**: 5.7.2
- **React version**:  16.14.0
- **Webpack version (if applicable)**: 5.74.0

### PR DESCRIPTION
**Pull request by andriivitiv**
Fixes https://github.com/wojtekmaj/react-pdf/issues/1062 - `Worker was terminated` error on document unmount if loading has not yet finished.

### CODE REVIEW

**Review by wojtekmaj — APPROVED** [review]

**Comment by wojtekmaj** [comment]
Thanks mate!

File: packages/react-pdf/src/Document.tsx [hunk 1]
```diff
@@ -534,7 +534,7 @@ const Document: React.ForwardRefExoticComponent<
         });
 
       return () => {
-        loadingTask.destroy();
+        loadingPromise.finally(() => loadingTask.destroy());
```
Comment (QichenZhu) [inline packages/react-pdf/src/Document.tsx:537]: This change introduced a race condition when quickly switching to a new PDF file. The cleanup could run asynchronously after the new PDF started loading and cause [a crash](https://github.com/Expensify/App/issues/76303#issuecomment-3642821395).

It's now fixed with PRs https://github.com/mozilla/pdf.js/pull/20503, https://github.com/Expensify/react-fast-pdf/pull/51, https://github.com/Expensify/react-fast-pdf/pull/52, and https://github.com/Expensify/App/pull/80160.
